### ISSUE TITLE
github.com/jteeuwen/go-pkg-xmlx  is not available, need replacement

### ISSUE THREAD

**Issue by linuxlibs** [stephenlyu/goqtuic#2]
hello,stephenlyu
   this day when I go get -u -v https://github.com/stephenlyu/goqtuic and found that github.com/jteeuwen/go-pkg-xmlx  repository is 404. and not easy to find its copy any more.
which will make goqtuic hard to compile for other people.

**Comment by linuxlibs** [comment]
https://github.com/dustywilson/go-pkg-xmlx 
good luck.

**Comment by creedr** [comment]
Another alternative for `go-pkg-xmlx` is found [https://github.com/mattn/go-pkg-xmlx](https://github.com/mattn/go-pkg-xmlx).
That repo includes a link to a reddit discussing what happened to `jteeuwen`.

If you have already run `go get -u -v https://github.com/stephenlyu/goqtuic`, then just open `goqtuic/parser/uiparser.go` and replace the `jteeuwen` import with `mattn` or `dustywilson` as linked above and rerun `go get -u -v https://github.com/stephenlyu/goqtuic`.
