### ISSUE TITLE
求加个开发者。

### ISSUE THREAD

**Issue by jifanchn** [stephenlyu/goqtuic#8]
Hi 大佬，最近想用一下therecipe/qt这个库，但是自己不会写widgets的各种配置，因此看到您这个库非常好。

有些指针，或者signal/slot的用起来不方便，想自己做些更改，是否可以让我成为库的开发者？

我保证不乱来。

**Comment by stephenlyu** [comment]
我已经把你加到了这个项目里。

**Comment by stephenlyu** [comment]
我现在没有时间维护这个项目，如果你有时间，帮忙把issue一起处理以下，谢谢～
